package com.parakhcomputer.web.model;

// Generated 27 Jun, 2011 1:35:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Palette generated by hbm2java
 */
@Entity
@Table(name = "Palette", catalog = "colorpalette")
public class Palette implements java.io.Serializable {

	private Integer paletteId;
	private Integer themeId;
	private String name;
	private String value;
	private Date created;

	public Palette() {
	}

	public Palette(String name, String value, Date created) {
		this.name = name;
		this.value = value;
		this.created = created;
	}

	public Palette(Integer themeId, String name, String value, Date created) {
		this.themeId = themeId;
		this.name = name;
		this.value = value;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Palette_ID", unique = true, nullable = false)
	public Integer getPaletteId() {
		return this.paletteId;
	}

	public void setPaletteId(Integer paletteId) {
		this.paletteId = paletteId;
	}

	@Column(name = "Theme_ID")
	public Integer getThemeId() {
		return this.themeId;
	}

	public void setThemeId(Integer themeId) {
		this.themeId = themeId;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, length = 6)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
