package com.parakhcomputer.web.model;

// Generated Mar 9, 2011 10:26:35 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school")
public class School implements java.io.Serializable {


	private static final long serialVersionUID = 5341926631245514679L;
	private Integer schoolId;
	private Long code;
	private String name;
	private String level;
	private String district;
	private Integer assemblyId;
	private String assemblyName;
	private String block;
	private String publicEducationCenter;
	private String panchayatMunicipal;
	private String villageWard;
	private String basahat;
	private Date created;

	public School() {
	}

	public School(Long code, String name, Date created) {
		this.code = code;
		this.name = name;
		this.created = created;
	}

	public School(Long code, String name, String level, String district,
			Integer assemblyId, String assemblyName, String block,
			String publicEducationCenter, String panchayatMunicipal,
			String villageWard, String basahat, Date created) {
		this.code = code;
		this.name = name;
		this.level = level;
		this.district = district;
		this.assemblyId = assemblyId;
		this.assemblyName = assemblyName;
		this.block = block;
		this.publicEducationCenter = publicEducationCenter;
		this.panchayatMunicipal = panchayatMunicipal;
		this.villageWard = villageWard;
		this.basahat = basahat;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "School_ID", unique = true, nullable = false)
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "Code" , nullable = false)
	public Long getCode() {
		return this.code;
	}

	public void setCode(Long code) {
		this.code = code;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "level", length = 100)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "District", length = 100)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "Assembly_id")
	public Integer getAssemblyId() {
		return this.assemblyId;
	}

	public void setAssemblyId(Integer assemblyId) {
		this.assemblyId = assemblyId;
	}

	@Column(name = "Assembly_name", length = 100)
	public String getAssemblyName() {
		return this.assemblyName;
	}

	public void setAssemblyName(String assemblyName) {
		this.assemblyName = assemblyName;
	}

	@Column(name = "Block", length = 100)
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	@Column(name = "Public_education_center", length = 100)
	public String getPublicEducationCenter() {
		return this.publicEducationCenter;
	}

	public void setPublicEducationCenter(String publicEducationCenter) {
		this.publicEducationCenter = publicEducationCenter;
	}

	@Column(name = "Panchayat_Municipal", length = 100)
	public String getPanchayatMunicipal() {
		return this.panchayatMunicipal;
	}

	public void setPanchayatMunicipal(String panchayatMunicipal) {
		this.panchayatMunicipal = panchayatMunicipal;
	}

	@Column(name = "Village_Ward", length = 100)
	public String getVillageWard() {
		return this.villageWard;
	}

	public void setVillageWard(String villageWard) {
		this.villageWard = villageWard;
	}

	@Column(name = "basahat", length = 100)
	public String getBasahat() {
		return this.basahat;
	}

	public void setBasahat(String basahat) {
		this.basahat = basahat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
