package com.parakhcomputer.web.model;

// Generated Mar 2, 2011 10:24:17 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentMarks generated by hbm2java
 */
@Entity
@Table(name = "student_marks")
public class StudentMarks implements java.io.Serializable {


	private static final long serialVersionUID = 5853362534861767478L;
	private Integer studentMarksId;
	private Integer personId;
	private Integer subjectId;
	private Integer examId;
	private Double obtain;
//	private String teacherComments;
    private Date created = null;

	public StudentMarks() {
	}

	public StudentMarks(Double obtain, String teacherComments) {
		this.obtain = obtain;
//		this.teacherComments = teacherComments;
	}

	public StudentMarks( Double obtain,
			Integer subjectId, String teacherComments) {
//		this.personId = personId;
//		this.examId = examId;
		this.obtain = obtain;
		this.subjectId = subjectId;
//		this.teacherComments = teacherComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "StudentMarks_ID", unique = true, nullable = false)
	public Integer getStudentMarksId() {
		return this.studentMarksId;
	}

	public void setStudentMarksId(Integer studentMarksId) {
		this.studentMarksId = studentMarksId;
	}

	@Column(name = "Person_ID")
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "Exam_ID")
	public Integer getExamId() {
		return this.examId;
	}

	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	@Column(name = "Obtain", nullable = false)
	public Double getObtain() {
		return this.obtain;
	}

	public void setObtain(Double obtain) {
		this.obtain = obtain;
	}

	@Column(name = "Subject_ID")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

/*	@Column(name = "Teacher_Comments", nullable = false, length = 100)
	public String getTeacherComments() {
		return this.teacherComments;
	}

	public void setTeacherComments(String teacherComments) {
		this.teacherComments = teacherComments;
	}
*/
 
    /**
     * Gets date created.
     */
    public Date getCreated() {
        return created;
    }

    /**
     * Sets date created.
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Returns a string representation of the object.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append(this.getClass().getName() + "-");
//TODO        sb.append("  addressId=" + addressId);
        
        return sb.toString();
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((this.studentMarksId == null) ? 0 : this.studentMarksId.hashCode());

        return result;
    }

    /**
     * Indicates whether some other object is equal to this one.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
/*
 * TODO
        final Caste other = (Caste) obj;

        if (this.casteId == null) {
            if (other.casteId != null)
                return false;
        } else if (!this.casteId.equals(other.casteId)) {
            return false;
        }

*/
        return true;
    }
    
    public boolean match(Integer personId, Integer subjectId, Integer examId){
    	return (this.personId==personId && this.subjectId == subjectId && this.examId == examId);
    }

}



