package com.parakhcomputer.web.model;

// Generated Mar 2, 2011 10:24:17 PM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubjectGroup generated by hbm2java
 */
@Entity
@Table(name = "subject_group")
public class SubjectGroup implements java.io.Serializable {


	private static final long serialVersionUID = 8294613742725758866L;
	private Integer groupId;
	private String name;
	private String description;
//	private Set<Subject> subject = new HashSet<Subject>(0);
	private Date created = null;
	
	public SubjectGroup() {
	}

	public SubjectGroup(String name, String description) {
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Group_ID", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectGroup")
	   /**
	    * Gets list of <code>School</code>es.
	    */
/*	   @OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.ALL)
	   @JoinColumn(name="GROUP_ID", nullable=false)	
	public Set<Subject> getSubject() {
		return this.subject;
	}

	public void setSubject(Set<Subject> subject) {
		this.subject = subject;
	}
*/
	
	
    

    /**
     * Gets date created.
     */
    public Date getCreated() {
        return created;
    }

    /**
     * Sets date created.
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * Returns a string representation of the object.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append(this.getClass().getName() + "-");
//TODO        sb.append("  addressId=" + addressId);
        
        return sb.toString();
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());

        return result;
    }

    /**
     * Indicates whether some other object is equal to this one.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
/*
 * TODO
        final Caste other = (Caste) obj;

        if (this.casteId == null) {
            if (other.casteId != null)
                return false;
        } else if (!this.casteId.equals(other.casteId)) {
            return false;
        }

*/
        return true;
    }

}



