package com.parakhcomputer.web.model;

// Generated 27 Jun, 2011 1:35:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "Theme", catalog = "colorpalette")
public class Theme implements java.io.Serializable {

	private Integer themeId;
	private String themeName;
	private String description;
	private Date created;

	public Theme() {
	}

	public Theme(String themeName, String description, Date created) {
		this.themeName = themeName;
		this.description = description;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Theme_ID", unique = true, nullable = false)
	public Integer getThemeId() {
		return this.themeId;
	}

	public void setThemeId(Integer themeId) {
		this.themeId = themeId;
	}

	@Column(name = "Theme_Name", nullable = false, length = 100)
	public String getThemeName() {
		return this.themeName;
	}

	public void setThemeName(String themeName) {
		this.themeName = themeName;
	}

	@Column(name = "Description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
